name: Build Yocto

on:
  workflow_call:
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.create-output.outputs.url }}

env:
  BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
  CACHE_DIR: /srv/gh-runners/quic-yocto
  KAS_REPO_REF_DIR: /srv/gh-runners/quic-yocto/kas-mirrors
  BASE_ARTIFACT_URL: https://quic-yocto-fileserver-1029608027416.us-central1.run.app

jobs:
  kas-mirror:
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - name: Update kas mirrors
        run: |
          for r in $(find ${KAS_REPO_REF_DIR}/* -maxdepth 0 -type d); do
            echo "pre-fetch: $r"
            git -C $r fetch --prune origin '+refs/*:refs/*'
          done

  kas-lock:
    needs:  kas-mirror
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run kas lock
        run: |
          kas dump --update --lock --inplace ci/base.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-check-layer:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          ci/yocto-check-layer.sh

  yocto-patchreview:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run Yocto patchreview
        run: |
          ci/yocto-patchreview.sh

  compile:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - qcs8300-ride-sx
          - qcs9075-iq-9075-evk
          - qcs9100-ride-sx
          - qrb2210-rb1-core-kit
          - qcom-armv8a
          - qcom-armv7a
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Kas build
        run: |
          export DL_DIR=${CACHE_DIR}/downloads
          export SSTATE_DIR=${CACHE_DIR}/sstate-cache
          export KAS_WORK_DIR=$PWD/../kas
          mkdir $KAS_WORK_DIR
          kas build ci/mirror.yml:ci/${{ matrix.machine }}.yml
          ci/yocto-pybootchartgui.sh && mv $KAS_WORK_DIR/build/buildchart.svg .

          if [ "${{ matrix.machine }}" = "qcom-arm8a" ]; then
            kas build ci/mirror.yml:ci/${{ matrix.machine }}.yml:initramfs-test.yml
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: buildchart-${{ matrix.machine }}
          path: buildchart.svg

      - name: Publish image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deploy_dir=../kas/build/tmp/deploy/images/${{matrix.machine}}
          find $deploy_dir/ -maxdepth 1 -name "*.rootfs*.qcomflash" -exec rm -rf {} \;

          # Instruct our file server to make these files available for download
          export URL="${BASE_ARTIFACT_URL}/${BUILD_ID}/${{ matrix.machine }}/"
          export BUILD_DIR="$(readlink -f $deploy_dir)"
          .github/workflows/publish_artifacts.py
          echo Image available at: ${URL}

  create-output:
    needs: compile
    outputs:
      url: ${{ steps.print-output.outputs.url }}
    runs-on: [self-hosted, x86]
    steps:
      - name: "Print output"
        id: print-output
        run: |
          build_url="${BASE_ARTIFACT_URL}/${BUILD_ID}"
          echo "Downloads URL: ${build_url}"
          echo "url=\"${build_url}\"" >> $GITHUB_OUTPUT
          echo "${build_url}" > build_url
      - name: Upload build URL
        uses: actions/upload-artifact@v4
        with:
          name: build_url
          path: build_url
